# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thanks',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='thanks',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thanks',
            name='name',
            field=models.CharField(default='noone', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thanks',
            name='repo',
            field=models.CharField(default='abc', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thanks',
            name='project_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='thanks',
            unique_together=set([('repo', 'name')]),
        ),
    ]
