# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0002_auto_20170722_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thanks',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
