# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0003_auto_20170725_0739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thanks',
            unique_together=set([]),
        ),
    ]
